name: VAE
channels:
  - numba
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - anaconda
  - pip:
    - matplotlib==3.3.4
    - pandas==1.2.1
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - seaborn==0.11.1
    - sklearn==0.0
