seed: 1265

model_params:
  in_channels: 3
  latent_dim: 128

exp_params:
  data_path: "./data/"
  model_path: "./models/"
  exp_name: "celeba"
  img_size: 64
  batch_size: 144
  LR: 0.0005
  epochs: 20
