seed: 1265
model: "celeba"

model_params:
  in_channels: 3
  latent_dim: 128

exp_params:
  result_path: "./results/"
  data_path: "./data/"
  exp_name: "celeba"
  img_size: 64
  batch_size: 144
  LR: 0.0005
  epochs: 200
