seed: 1265
model: 'latent_ode'

model_params:
  latent_dim: 4
  rnn_hidden_dim: 32
  dec_hidden_dim: 32
  hidden_dim: 32
  device: 'cuda'

data_params:
  n_spiral: 1000
  n_channel: 2
  n_frames: 10
  n_total: 500
  noise_std: .1

exp_params:
  result_path: "./results/"
  exp_name: "latent_ode_test"
  batch_size: 32
  LR: 0.0001
  epochs: 1000
