seed: 1265

model_params:
  latent_dim: 4
  rnn_hidden_dim: 32
  dec_hidden_dim: 32
  hidden_dim: 32
  device: 'cuda'

data_params:
  n_spiral: 14
  n_channel: 2
  n_frames: 10
  n_total: 500
  noise_std: .1

exp_params:
  data_path: "./data/latent_ode/"
  model_path: "./models/latent_ode/"
  exp_name: "test1"
  batch_size: 32
  LR: 0.0005
  epochs: 500
